import type { Metadata } from "next";
import {
  Roboto,
  Roboto_Serif,
  Roboto_Mono,
  Roboto_Slab,
} from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: "100",
  subsets: ["latin"],
  variable: "--font-roboto",
});
const robotoSerif = Roboto_Serif({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-serif",
});
const robotoMono = Roboto_Mono({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-mono",
});
const robotoSlab = Roboto_Slab({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-slab",
});

export const metadata: Metadata = {
  title: "Holister",
  description: "Generated by Holister",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${robotoSerif.variable} ${robotoMono.variable} ${robotoSlab.variable} bg-[ #F5F5F5 ] overflow-x-hidden overflow-y-scroll`}
      >
        {children}
      </body>
    </html>
  );
}
